@startuml music-store-phase-4.puml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
HIDE_STEREOTYPE()

skinparam backgroundColor transparent
skinparam monochrome reverse

Container_Boundary(musicStore, "music-store") {
    Component(guitar, "Guitar", "Class", "-name: String\n-amplifier: Amplifier")
    Component(amplifier, "Amplifier", "Class", "-stockEffects: EffectLoop\n-auxEffects: EffectLoop")
    Component(effect, "Effect", "Interface", "+apply()")
    Component(effectLoop, "EffectLoop", "Class", "-effects: Set<Effect>")
    Component(delay, "Delay", "Class", "-timeInMs: int")
    Component(reverb, "Reverb", "Class", "-roomSize: int")
    Component(overdrive, "Overdrive", "Class", "-gain: int")
    Component(tremolo, "Tremolo", "Class", "-depth:int\n-rate: int")
    Component(tuner, "Tuner", "Class", "-pitchInHz: int\n+isInTune(Guitar)")

    guitar --> amplifier
    amplifier --> effectLoop
    effectLoop -r-> effect

    delay -u-|> effect
    reverb -u-|> effect
    effectLoop -r-|> effect
    overdrive --|> effect
    tremolo --|> effect
    tuner -l-|> effect
}

@enduml